/**
 * `@slopcad/cad-jsx`: author CAD models as React element trees, compiled
 * deterministically to the `@slopcad/cad-core` command vocabulary.
 *
 * The public surface is the element vocabulary (`./elements.ts`) and the
 * compiler entry point (`compileModel` from `./compiler.ts`). See the
 * package README for the authoring guide, the id assignment scheme, the
 * reference mechanisms (`<Use>` for shared features, `ref_…`/`dtm_…`
 * props for records minted outside the tree, `<Sketch id=…>` siblings for
 * sketch-consuming elements), and the determinism guarantees.
 */

export type {
  ArcProps,
  BodyProps,
  BoxProps,
  CadElementKind,
  CadElementTag,
  ChamferProps,
  CircleProps,
  ConeProps,
  CylinderProps,
  DeleteFaceProps,
  DimensionalProp,
  DatumProp,
  EllipseProps,
  FeatureRefProp,
  FilletProps,
  HelixProps,
  HoleProps,
  HoleType,
  Handedness,
  IntersectProps,
  LineProps,
  MirrorProps,
  MoveFaceProps,
  ParameterProps,
  PatternCircularProps,
  PatternLinearProps,
  PatternOrientation,
  PatternPathProps,
  PointProps,
  PolygonFit,
  PolygonProps,
  RectangleProps,
  ReferenceProp,
  ReplaceFaceProps,
  RibProps,
  ScaleProps,
  ShellProps,
  SketchProps,
  SketchRefProp,
  SlotProps,
  SlotVariant,
  SplineFlavor,
  SplinePointProp,
  SplineProps,
  SphereProps,
  SplitProps,
  SubtractProps,
  ThreadMode,
  ThreadProps,
  TranslateProps,
  UnionProps,
  UseProps,
  Vec3Prop,
  WorldAxis,
} from "./elements";
export {
  Arc,
  Body,
  Box,
  CAD_ELEMENT_KINDS,
  Chamfer,
  Circle,
  Cone,
  Cylinder,
  defineCadElement,
  DeleteFace,
  Ellipse,
  Fillet,
  Helix,
  Hole,
  Intersect,
  isCadElementTag,
  Line,
  Mirror,
  MoveFace,
  Parameter,
  PatternCircular,
  PatternLinear,
  PatternPath,
  Point,
  Polygon,
  Rectangle,
  ReplaceFace,
  Rib,
  Scale,
  Shell,
  Sketch,
  Slot,
  Sphere,
  Split,
  Spline,
  Subtract,
  Thread,
  Translate,
  Union,
  Use,
} from "./elements";

export type { CadJsxCompileError, CadJsxErrorCode } from "./compiler";
export { CAD_JSX_ERROR_CODES, compileModel } from "./compiler";
