/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IoRouteImport } from './routes/io'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RenderRouteImport } from './routes/render'
import { Route as SpikeRouteImport } from './routes/spike'
import { Route as UiViewportRouteImport } from './routes/ui-viewport'
import { Route as WorkbenchRouteImport } from './routes/workbench'
import { Route as WorkerRouteImport } from './routes/worker'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiIoImport3mfRouteImport } from './routes/api/io/import-3mf'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IoRoute = IoRouteImport.update({
  id: '/io',
  path: '/io',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RenderRoute = RenderRouteImport.update({
  id: '/render',
  path: '/render',
  getParentRoute: () => rootRouteImport,
} as any)
const SpikeRoute = SpikeRouteImport.update({
  id: '/spike',
  path: '/spike',
  getParentRoute: () => rootRouteImport,
} as any)
const UiViewportRoute = UiViewportRouteImport.update({
  id: '/ui-viewport',
  path: '/ui-viewport',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerRoute = WorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIoImport3mfRoute = ApiIoImport3mfRouteImport.update({
  id: '/api/io/import-3mf',
  path: '/api/io/import-3mf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/io': typeof IoRoute
  '/login': typeof LoginRoute
  '/render': typeof RenderRoute
  '/spike': typeof SpikeRoute
  '/ui-viewport': typeof UiViewportRoute
  '/workbench': typeof WorkbenchRoute
  '/worker': typeof WorkerRoute
  '/dashboard': typeof AuthDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/io/import-3mf': typeof ApiIoImport3mfRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/io': typeof IoRoute
  '/login': typeof LoginRoute
  '/render': typeof RenderRoute
  '/spike': typeof SpikeRoute
  '/ui-viewport': typeof UiViewportRoute
  '/workbench': typeof WorkbenchRoute
  '/worker': typeof WorkerRoute
  '/dashboard': typeof AuthDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/io/import-3mf': typeof ApiIoImport3mfRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/io': typeof IoRoute
  '/login': typeof LoginRoute
  '/render': typeof RenderRoute
  '/spike': typeof SpikeRoute
  '/ui-viewport': typeof UiViewportRoute
  '/workbench': typeof WorkbenchRoute
  '/worker': typeof WorkerRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/io/import-3mf': typeof ApiIoImport3mfRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/io'
    | '/login'
    | '/render'
    | '/spike'
    | '/ui-viewport'
    | '/workbench'
    | '/worker'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/io/import-3mf'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/io'
    | '/login'
    | '/render'
    | '/spike'
    | '/ui-viewport'
    | '/workbench'
    | '/worker'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/io/import-3mf'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/io'
    | '/login'
    | '/render'
    | '/spike'
    | '/ui-viewport'
    | '/workbench'
    | '/worker'
    | '/_auth/dashboard'
    | '/api/auth/$'
    | '/api/io/import-3mf'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  IoRoute: typeof IoRoute
  LoginRoute: typeof LoginRoute
  RenderRoute: typeof RenderRoute
  SpikeRoute: typeof SpikeRoute
  UiViewportRoute: typeof UiViewportRoute
  WorkbenchRoute: typeof WorkbenchRoute
  WorkerRoute: typeof WorkerRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiIoImport3mfRoute: typeof ApiIoImport3mfRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/io': {
      id: '/io'
      path: '/io'
      fullPath: '/io'
      preLoaderRoute: typeof IoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/render': {
      id: '/render'
      path: '/render'
      fullPath: '/render'
      preLoaderRoute: typeof RenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spike': {
      id: '/spike'
      path: '/spike'
      fullPath: '/spike'
      preLoaderRoute: typeof SpikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-viewport': {
      id: '/ui-viewport'
      path: '/ui-viewport'
      fullPath: '/ui-viewport'
      preLoaderRoute: typeof UiViewportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbench': {
      id: '/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker': {
      id: '/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof WorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/io/import-3mf': {
      id: '/api/io/import-3mf'
      path: '/api/io/import-3mf'
      fullPath: '/api/io/import-3mf'
      preLoaderRoute: typeof ApiIoImport3mfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  IoRoute: IoRoute,
  LoginRoute: LoginRoute,
  RenderRoute: RenderRoute,
  SpikeRoute: SpikeRoute,
  UiViewportRoute: UiViewportRoute,
  WorkbenchRoute: WorkbenchRoute,
  WorkerRoute: WorkerRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiIoImport3mfRoute: ApiIoImport3mfRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
