/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DrawingsRouteImport } from './routes/drawings'
import { Route as IoRouteImport } from './routes/io'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PerfRouteImport } from './routes/perf'
import { Route as RenderRouteImport } from './routes/render'
import { Route as SpikeRouteImport } from './routes/spike'
import { Route as UiViewportRouteImport } from './routes/ui-viewport'
import { Route as WorkbenchRouteImport } from './routes/workbench'
import { Route as WorkbenchAssemblyRouteImport } from './routes/workbench-assembly'
import { Route as WorkbenchAssemblyMotionRouteImport } from './routes/workbench-assembly-motion'
import { Route as WorkbenchChainRouteImport } from './routes/workbench-chain'
import { Route as WorkbenchCompleteRouteImport } from './routes/workbench-complete'
import { Route as WorkbenchCompleteOcctRouteImport } from './routes/workbench-complete-occt'
import { Route as WorkbenchDrawingRouteImport } from './routes/workbench-drawing'
import { Route as WorkerRouteImport } from './routes/worker'
import { Route as WorkerFilletRouteImport } from './routes/worker-fillet'
import { Route as WorkerOcctRouteImport } from './routes/worker-occt'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as ComponentsComponentIdRouteImport } from './routes/components.$componentId'
import { Route as AuthDocumentsDocumentIdRouteImport } from './routes/_auth/documents.$documentId'
import { Route as AuthProjectsIndexRouteImport } from './routes/_auth/projects.index'
import { Route as AuthProjectsProjectIdRouteImport } from './routes/_auth/projects.$projectId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiIoImport3mfRouteImport } from './routes/api/io/import-3mf'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsRoute = DrawingsRouteImport.update({
  id: '/drawings',
  path: '/drawings',
  getParentRoute: () => rootRouteImport,
} as any)
const IoRoute = IoRouteImport.update({
  id: '/io',
  path: '/io',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfRoute = PerfRouteImport.update({
  id: '/perf',
  path: '/perf',
  getParentRoute: () => rootRouteImport,
} as any)
const RenderRoute = RenderRouteImport.update({
  id: '/render',
  path: '/render',
  getParentRoute: () => rootRouteImport,
} as any)
const SpikeRoute = SpikeRouteImport.update({
  id: '/spike',
  path: '/spike',
  getParentRoute: () => rootRouteImport,
} as any)
const UiViewportRoute = UiViewportRouteImport.update({
  id: '/ui-viewport',
  path: '/ui-viewport',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchAssemblyRoute = WorkbenchAssemblyRouteImport.update({
  id: '/workbench-assembly',
  path: '/workbench-assembly',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchAssemblyMotionRoute = WorkbenchAssemblyMotionRouteImport.update({
  id: '/workbench-assembly-motion',
  path: '/workbench-assembly-motion',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchChainRoute = WorkbenchChainRouteImport.update({
  id: '/workbench-chain',
  path: '/workbench-chain',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchCompleteRoute = WorkbenchCompleteRouteImport.update({
  id: '/workbench-complete',
  path: '/workbench-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchCompleteOcctRoute = WorkbenchCompleteOcctRouteImport.update({
  id: '/workbench-complete-occt',
  path: '/workbench-complete-occt',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchDrawingRoute = WorkbenchDrawingRouteImport.update({
  id: '/workbench-drawing',
  path: '/workbench-drawing',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerRoute = WorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerFilletRoute = WorkerFilletRouteImport.update({
  id: '/worker-fillet',
  path: '/worker-fillet',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerOcctRoute = WorkerOcctRouteImport.update({
  id: '/worker-occt',
  path: '/worker-occt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ComponentsComponentIdRoute = ComponentsComponentIdRouteImport.update({
  id: '/components/$componentId',
  path: '/components/$componentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDocumentsDocumentIdRoute = AuthDocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthProjectsIndexRoute = AuthProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthProjectsProjectIdRoute = AuthProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIoImport3mfRoute = ApiIoImport3mfRouteImport.update({
  id: '/api/io/import-3mf',
  path: '/api/io/import-3mf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/drawings': typeof DrawingsRoute
  '/io': typeof IoRoute
  '/login': typeof LoginRoute
  '/perf': typeof PerfRoute
  '/render': typeof RenderRoute
  '/spike': typeof SpikeRoute
  '/ui-viewport': typeof UiViewportRoute
  '/workbench': typeof WorkbenchRoute
  '/workbench-assembly': typeof WorkbenchAssemblyRoute
  '/workbench-assembly-motion': typeof WorkbenchAssemblyMotionRoute
  '/workbench-chain': typeof WorkbenchChainRoute
  '/workbench-complete': typeof WorkbenchCompleteRoute
  '/workbench-complete-occt': typeof WorkbenchCompleteOcctRoute
  '/workbench-drawing': typeof WorkbenchDrawingRoute
  '/worker': typeof WorkerRoute
  '/worker-fillet': typeof WorkerFilletRoute
  '/worker-occt': typeof WorkerOcctRoute
  '/dashboard': typeof AuthDashboardRoute
  '/components/$componentId': typeof ComponentsComponentIdRoute
  '/documents/$documentId': typeof AuthDocumentsDocumentIdRoute
  '/projects/$projectId': typeof AuthProjectsProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/io/import-3mf': typeof ApiIoImport3mfRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/projects/': typeof AuthProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/drawings': typeof DrawingsRoute
  '/io': typeof IoRoute
  '/login': typeof LoginRoute
  '/perf': typeof PerfRoute
  '/render': typeof RenderRoute
  '/spike': typeof SpikeRoute
  '/ui-viewport': typeof UiViewportRoute
  '/workbench': typeof WorkbenchRoute
  '/workbench-assembly': typeof WorkbenchAssemblyRoute
  '/workbench-assembly-motion': typeof WorkbenchAssemblyMotionRoute
  '/workbench-chain': typeof WorkbenchChainRoute
  '/workbench-complete': typeof WorkbenchCompleteRoute
  '/workbench-complete-occt': typeof WorkbenchCompleteOcctRoute
  '/workbench-drawing': typeof WorkbenchDrawingRoute
  '/worker': typeof WorkerRoute
  '/worker-fillet': typeof WorkerFilletRoute
  '/worker-occt': typeof WorkerOcctRoute
  '/dashboard': typeof AuthDashboardRoute
  '/components/$componentId': typeof ComponentsComponentIdRoute
  '/documents/$documentId': typeof AuthDocumentsDocumentIdRoute
  '/projects/$projectId': typeof AuthProjectsProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/io/import-3mf': typeof ApiIoImport3mfRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/projects': typeof AuthProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/docs': typeof DocsRoute
  '/drawings': typeof DrawingsRoute
  '/io': typeof IoRoute
  '/login': typeof LoginRoute
  '/perf': typeof PerfRoute
  '/render': typeof RenderRoute
  '/spike': typeof SpikeRoute
  '/ui-viewport': typeof UiViewportRoute
  '/workbench': typeof WorkbenchRoute
  '/workbench-assembly': typeof WorkbenchAssemblyRoute
  '/workbench-assembly-motion': typeof WorkbenchAssemblyMotionRoute
  '/workbench-chain': typeof WorkbenchChainRoute
  '/workbench-complete': typeof WorkbenchCompleteRoute
  '/workbench-complete-occt': typeof WorkbenchCompleteOcctRoute
  '/workbench-drawing': typeof WorkbenchDrawingRoute
  '/worker': typeof WorkerRoute
  '/worker-fillet': typeof WorkerFilletRoute
  '/worker-occt': typeof WorkerOcctRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/components/$componentId': typeof ComponentsComponentIdRoute
  '/_auth/documents/$documentId': typeof AuthDocumentsDocumentIdRoute
  '/_auth/projects/$projectId': typeof AuthProjectsProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/io/import-3mf': typeof ApiIoImport3mfRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_auth/projects/': typeof AuthProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/drawings'
    | '/io'
    | '/login'
    | '/perf'
    | '/render'
    | '/spike'
    | '/ui-viewport'
    | '/workbench'
    | '/workbench-assembly'
    | '/workbench-assembly-motion'
    | '/workbench-chain'
    | '/workbench-complete'
    | '/workbench-complete-occt'
    | '/workbench-drawing'
    | '/worker'
    | '/worker-fillet'
    | '/worker-occt'
    | '/dashboard'
    | '/components/$componentId'
    | '/documents/$documentId'
    | '/projects/$projectId'
    | '/api/auth/$'
    | '/api/io/import-3mf'
    | '/api/trpc/$'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/drawings'
    | '/io'
    | '/login'
    | '/perf'
    | '/render'
    | '/spike'
    | '/ui-viewport'
    | '/workbench'
    | '/workbench-assembly'
    | '/workbench-assembly-motion'
    | '/workbench-chain'
    | '/workbench-complete'
    | '/workbench-complete-occt'
    | '/workbench-drawing'
    | '/worker'
    | '/worker-fillet'
    | '/worker-occt'
    | '/dashboard'
    | '/components/$componentId'
    | '/documents/$documentId'
    | '/projects/$projectId'
    | '/api/auth/$'
    | '/api/io/import-3mf'
    | '/api/trpc/$'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/docs'
    | '/drawings'
    | '/io'
    | '/login'
    | '/perf'
    | '/render'
    | '/spike'
    | '/ui-viewport'
    | '/workbench'
    | '/workbench-assembly'
    | '/workbench-assembly-motion'
    | '/workbench-chain'
    | '/workbench-complete'
    | '/workbench-complete-occt'
    | '/workbench-drawing'
    | '/worker'
    | '/worker-fillet'
    | '/worker-occt'
    | '/_auth/dashboard'
    | '/components/$componentId'
    | '/_auth/documents/$documentId'
    | '/_auth/projects/$projectId'
    | '/api/auth/$'
    | '/api/io/import-3mf'
    | '/api/trpc/$'
    | '/_auth/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DocsRoute: typeof DocsRoute
  DrawingsRoute: typeof DrawingsRoute
  IoRoute: typeof IoRoute
  LoginRoute: typeof LoginRoute
  PerfRoute: typeof PerfRoute
  RenderRoute: typeof RenderRoute
  SpikeRoute: typeof SpikeRoute
  UiViewportRoute: typeof UiViewportRoute
  WorkbenchRoute: typeof WorkbenchRoute
  WorkbenchAssemblyRoute: typeof WorkbenchAssemblyRoute
  WorkbenchAssemblyMotionRoute: typeof WorkbenchAssemblyMotionRoute
  WorkbenchChainRoute: typeof WorkbenchChainRoute
  WorkbenchCompleteRoute: typeof WorkbenchCompleteRoute
  WorkbenchCompleteOcctRoute: typeof WorkbenchCompleteOcctRoute
  WorkbenchDrawingRoute: typeof WorkbenchDrawingRoute
  WorkerRoute: typeof WorkerRoute
  WorkerFilletRoute: typeof WorkerFilletRoute
  WorkerOcctRoute: typeof WorkerOcctRoute
  ComponentsComponentIdRoute: typeof ComponentsComponentIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiIoImport3mfRoute: typeof ApiIoImport3mfRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings': {
      id: '/drawings'
      path: '/drawings'
      fullPath: '/drawings'
      preLoaderRoute: typeof DrawingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/io': {
      id: '/io'
      path: '/io'
      fullPath: '/io'
      preLoaderRoute: typeof IoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perf': {
      id: '/perf'
      path: '/perf'
      fullPath: '/perf'
      preLoaderRoute: typeof PerfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/render': {
      id: '/render'
      path: '/render'
      fullPath: '/render'
      preLoaderRoute: typeof RenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spike': {
      id: '/spike'
      path: '/spike'
      fullPath: '/spike'
      preLoaderRoute: typeof SpikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui-viewport': {
      id: '/ui-viewport'
      path: '/ui-viewport'
      fullPath: '/ui-viewport'
      preLoaderRoute: typeof UiViewportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbench': {
      id: '/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbench-assembly': {
      id: '/workbench-assembly'
      path: '/workbench-assembly'
      fullPath: '/workbench-assembly'
      preLoaderRoute: typeof WorkbenchAssemblyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbench-assembly-motion': {
      id: '/workbench-assembly-motion'
      path: '/workbench-assembly-motion'
      fullPath: '/workbench-assembly-motion'
      preLoaderRoute: typeof WorkbenchAssemblyMotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbench-chain': {
      id: '/workbench-chain'
      path: '/workbench-chain'
      fullPath: '/workbench-chain'
      preLoaderRoute: typeof WorkbenchChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbench-complete': {
      id: '/workbench-complete'
      path: '/workbench-complete'
      fullPath: '/workbench-complete'
      preLoaderRoute: typeof WorkbenchCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbench-complete-occt': {
      id: '/workbench-complete-occt'
      path: '/workbench-complete-occt'
      fullPath: '/workbench-complete-occt'
      preLoaderRoute: typeof WorkbenchCompleteOcctRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbench-drawing': {
      id: '/workbench-drawing'
      path: '/workbench-drawing'
      fullPath: '/workbench-drawing'
      preLoaderRoute: typeof WorkbenchDrawingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker': {
      id: '/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof WorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker-fillet': {
      id: '/worker-fillet'
      path: '/worker-fillet'
      fullPath: '/worker-fillet'
      preLoaderRoute: typeof WorkerFilletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker-occt': {
      id: '/worker-occt'
      path: '/worker-occt'
      fullPath: '/worker-occt'
      preLoaderRoute: typeof WorkerOcctRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/components/$componentId': {
      id: '/components/$componentId'
      path: '/components/$componentId'
      fullPath: '/components/$componentId'
      preLoaderRoute: typeof ComponentsComponentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/documents/$documentId': {
      id: '/_auth/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof AuthDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/projects/': {
      id: '/_auth/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthProjectsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/projects/$projectId': {
      id: '/_auth/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthProjectsProjectIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/io/import-3mf': {
      id: '/api/io/import-3mf'
      path: '/api/io/import-3mf'
      fullPath: '/api/io/import-3mf'
      preLoaderRoute: typeof ApiIoImport3mfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthDocumentsDocumentIdRoute: typeof AuthDocumentsDocumentIdRoute
  AuthProjectsProjectIdRoute: typeof AuthProjectsProjectIdRoute
  AuthProjectsIndexRoute: typeof AuthProjectsIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthDocumentsDocumentIdRoute: AuthDocumentsDocumentIdRoute,
  AuthProjectsProjectIdRoute: AuthProjectsProjectIdRoute,
  AuthProjectsIndexRoute: AuthProjectsIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DocsRoute: DocsRoute,
  DrawingsRoute: DrawingsRoute,
  IoRoute: IoRoute,
  LoginRoute: LoginRoute,
  PerfRoute: PerfRoute,
  RenderRoute: RenderRoute,
  SpikeRoute: SpikeRoute,
  UiViewportRoute: UiViewportRoute,
  WorkbenchRoute: WorkbenchRoute,
  WorkbenchAssemblyRoute: WorkbenchAssemblyRoute,
  WorkbenchAssemblyMotionRoute: WorkbenchAssemblyMotionRoute,
  WorkbenchChainRoute: WorkbenchChainRoute,
  WorkbenchCompleteRoute: WorkbenchCompleteRoute,
  WorkbenchCompleteOcctRoute: WorkbenchCompleteOcctRoute,
  WorkbenchDrawingRoute: WorkbenchDrawingRoute,
  WorkerRoute: WorkerRoute,
  WorkerFilletRoute: WorkerFilletRoute,
  WorkerOcctRoute: WorkerOcctRoute,
  ComponentsComponentIdRoute: ComponentsComponentIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiIoImport3mfRoute: ApiIoImport3mfRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
