/**
 * Public entry of `@slopcad/cad-core`, the kernel-neutral CAD document
 * model plus the renderer-neutral render projection. This package carries
 * no React, Three.js, DOM, or geometry-kernel dependencies; every layer
 * above it — kernels, renderers, workers — builds on the API exported here.
 */
export type {
  AnyCadId,
  BodyId,
  CadId,
  CadIdKind,
  ConfigurationId,
  CurveId,
  DatumId,
  SectionId,
  DocumentId,
  DrawingViewId,
  FeatureId,
  IdGenerator,
  IdGeneratorErrorCode,
  IdGeneratorState,
  IdParseError,
  JointId,
  MateId,
  OccurrenceId,
  ParameterId,
  ParsedCadId,
  ReferenceId,
  SheetId,
  SketchDocumentId,
} from "./ids";
export type {
  Appearance,
  AppearanceErrorCode,
  AppearanceLibraryEntry,
  AppearanceTextureName,
  FaceAppearanceOverride,
} from "./appearance";
export {
  APPEARANCE_ERROR_CODES,
  APPEARANCE_LIBRARY,
  APPEARANCE_TEXTURES,
  appearanceLibraryEntry,
  appearancesEqual,
  BODY_FACE_APPEARANCE_LIMIT,
  faceOverrideInSnapshot,
  parseAppearance,
  serializeAppearance,
} from "./appearance";
export {
  type CurvePoint3,
  CURVE_ERROR_CODES,
  type CurveErrorCode,
  type CurveParseError,
  type CurveProblem,
  type EquationCurveAst,
  type EquationCurvePayload,
  type HelixCurvePayload,
  type InterpolatedSplinePayload,
  type ControlSplinePayload,
  type SerializedCurve,
  type CurveDimensional,
  CURVE_POINT_MIN_SPACING_MM,
  CURVE_EQUATION_IDENTIFIER,
  curveRecordProblems,
  helixCurvePayload,
  parseEquationCurveAst,
  parseSerializedCurve,
} from "./curve";
export {
  CAD_ID_KINDS,
  CAD_ID_MAX_PAYLOAD_LENGTH,
  CAD_ID_PREFIXES,
  CadIdGeneratorExhaustedError,
  CadIdValidationError,
  createBodyId,
  createCurveId,
  createConfigurationId,
  createDatumId,
  createSectionId,
  createDocumentId,
  createDrawingViewId,
  createFeatureId,
  createIdGenerator,
  createJointId,
  createMateId,
  createOccurrenceId,
  createParameterId,
  createReferenceId,
  createSheetId,
  createSketchDocumentId,
  ID_ERROR_CODES,
  ID_GENERATOR_ERROR_CODES,
  parseAnyCadId,
  parseBodyId,
  parseConfigurationId,
  parseCurveId,
  parseDatumId,
  parseDrawingViewId,
  parseJointId,
  parseMateId,
  parseOccurrenceId,
  parseSectionId,
  parseDocumentId,
  parseFeatureId,
  parseParameterId,
  parseReferenceId,
  parseSheetId,
  parseSketchDocumentId,
} from "./ids";
export type {
  Diagnostic,
  DiagnosticCode,
  DiagnosticDataValue,
  DiagnosticLocation,
  DiagnosticParseError,
  DiagnosticParseErrorCode,
  DiagnosticSeverity,
} from "./diagnostics";
export {
  compareSeverities,
  DIAGNOSTIC_CODES,
  DIAGNOSTIC_SEVERITIES,
  DIAGNOSTIC_SEVERITY_ORDER,
  isDiagnosticCode,
  isDiagnosticSeverity,
  parseDiagnostic,
} from "./diagnostics";
export type {
  AngleUnit,
  AnyUnit,
  AreaUnit,
  Dimension,
  DimensionlessUnit,
  LengthUnit,
  ParsedUnit,
  UnitErrorCode,
  UnitOf,
  UnitParseError,
  VolumeUnit,
} from "./units";
export {
  ANGLE_UNITS,
  AREA_UNITS,
  CANONICAL_UNITS,
  CONVERSION_TOLERANCE,
  DIMENSIONS,
  DIMENSIONLESS_UNIT,
  isAngleUnit,
  isAreaUnit,
  isDimension,
  isLengthUnit,
  isUnitToken,
  isVolumeUnit,
  LENGTH_UNITS,
  parseUnit,
  UNIT_ERROR_CODES,
  unitDimension,
  VOLUME_UNITS,
} from "./units";
export type {
  AngleValue,
  AnyDimensionalValue,
  AreaValue,
  DimensionalArithmeticFailure,
  DimensionalErrorCode,
  DimensionalOperation,
  DimensionalParseError,
  DimensionalValue,
  DimensionlessValue,
  LengthValue,
  SerializedDimensionalValue,
  VolumeValue,
} from "./dimensional";
export {
  add,
  addValues,
  angle,
  area,
  convert,
  DIMENSIONAL_ERROR_CODES,
  DimensionalArithmeticValidationError,
  dimensionless,
  DimensionalValueValidationError,
  divide,
  divideValues,
  equalQuantity,
  length,
  multiply,
  multiplyValues,
  parseDimensionalValue,
  serializeDimensionalValue,
  serializeDimensionalValueResult,
  subtract,
  subtractValues,
  toCanonical,
  valueIn,
  volume,
} from "./dimensional";
export type {
  BinaryNode,
  BinaryOperator,
  CallNode,
  ExpressionAstError,
  ExpressionAstErrorCode,
  ExpressionFunction,
  ExpressionNode,
  ExpressionNodeKind,
  IdentifierNode,
  NumberNode,
  UnaryNode,
  UnitLiteralNode,
} from "./expression";
export {
  BINARY_OPERATORS,
  EXPRESSION_AST_ERROR_CODES,
  EXPRESSION_FUNCTIONS,
  EXPRESSION_NODE_KINDS,
  extractExpressionDependencies,
  isBinaryOperator,
  isExpressionFunction,
  isExpressionIdentifierName,
  isValidCallArity,
  MAX_EXPRESSION_DEPTH,
  MAX_EXPRESSION_IDENTIFIER_LENGTH,
  parseExpressionAst,
  printExpression,
} from "./expression";
export type {
  ExpressionParseError,
  ExpressionParseErrorCode,
} from "./expression-parser";
export {
  EXPRESSION_PARSE_ERROR_CODES,
  parseExpression,
} from "./expression-parser";
export type {
  ExpressionEnvironment,
  ExpressionEvaluationError,
  ExpressionEvaluationErrorCode,
} from "./expression-evaluator";
export {
  evaluateExpression,
  EXPRESSION_EVALUATION_ERROR_CODES,
} from "./expression-evaluator";
export type {
  Parameter,
  ParameterCollection,
  ParameterError,
  ParameterErrorCode,
  ParameterInput,
  ParameterMetadata,
  ParameterMetadataValue,
  SerializedParameter,
  SerializedParameterCollection,
} from "./parameter";
export type {
  ConfigurationError,
  ConfigurationErrorCode,
  ConfigurationParameterOverride,
  ConfigurationParameterOverrideInput,
  CsvParameterRow,
  DocumentConfiguration,
  DocumentConfigurationInput,
  EffectiveDocumentView,
  SerializedDocumentConfiguration,
} from "./configuration";
export {
  applyDocumentConfiguration,
  buildDocumentConfiguration,
  CONFIGURATION_ERROR_CODES,
  PARAMETER_TABLE_CSV_HEADER,
  overridesFromCsvRows,
  parseDocumentConfiguration,
  parseParameterTableCsv,
  serializeDocumentConfiguration,
  serializeParameterTableCsv,
} from "./configuration";
export {
  addParameter,
  EMPTY_PARAMETER_COLLECTION,
  findParameterByName,
  getParameter,
  PARAMETER_ERROR_CODES,
  parameterEnvironment,
  parseParameter,
  parseParameterCollection,
  removeParameter,
  serializeParameter,
  serializeParameterCollection,
  updateParameterExpression,
  updateParameterMetadata,
  updateParameterValue,
} from "./parameter";
export {
  findParameterCycle,
  parameterDependencyEdges,
} from "./parameter-graph";
export type {
  CadCommand,
  CadCommandType,
  CommandApplyError,
  CommandError,
  CommandErrorCode,
  SerializedCadCommand,
} from "./command";
export {
  applyCommand,
  CAD_COMMAND_TYPES,
  COMMAND_ERROR_CODES,
  isCadCommandType,
  parseCommand,
  serializeCommand,
} from "./command";
export type {
  CadTransaction,
  SerializedCadTransaction,
  TransactionError,
  TransactionErrorCode,
} from "./transaction";
export {
  applyTransaction,
  parseTransaction,
  serializeTransaction,
  TRANSACTION_ERROR_CODES,
} from "./transaction";
export type {
  DocumentHistory,
  HistoryEntry,
  HistoryError,
  HistoryErrorCode,
  HistoryMove,
} from "./history";
export {
  canRedo,
  canUndo,
  createDocumentHistory,
  currentDocument,
  HISTORY_ERROR_CODES,
  redoHistory,
  recordTransaction,
  undoHistory,
} from "./history";
export type { CadSession } from "./session";
export {
  applySessionCommand,
  applySessionTransaction,
  createSession,
  redoSession,
  undoSession,
} from "./session";
export type {
  FeatureGraphError,
  FeatureGraphErrorCode,
  FeatureGraphNodeId,
  FeatureGraphSourceId,
} from "./feature-graph";
export {
  affectedFeatures,
  FEATURE_GRAPH_ERROR_CODES,
  featureDependencyEdges,
  featureEvaluationOrder,
  findFeatureCycle,
} from "./feature-graph";
export type {
  FeatureHistoryError,
  FeatureHistoryErrorCode,
  FeatureRollbackPoint,
  FeatureTimelineEntry,
  FeatureTimelineEntryDiagnostic,
  FeatureTimelineInput,
  FeatureTimelineStatus,
} from "./feature-history";
export {
  documentChangeInvalidations,
  FEATURE_HISTORY_ERROR_CODES,
  FEATURE_TIMELINE_STATUSES,
  featureTimeline,
  isFeatureTimelineStatus,
  parseFeatureRollbackShape,
  reorderFeatureRecords,
  rollbackZoneBoundary,
} from "./feature-history";
export type {
  Body,
  BodyAddResult,
  BodyInput,
  CadDocument,
  DocumentCurve,
  DocumentCurveAddResult,
  DocumentCurveInput,
  DocumentDatum,
  DocumentSection,
  DocumentDatumAddResult,
  DocumentDatumInput,
  DocumentEntity,
  DocumentReference,
  DocumentReferenceAddResult,
  DocumentReferenceInput,
  DocumentSketch,
  DocumentSketchInput,
  DocumentError,
  DocumentErrorCode,
  DocumentParameterAddResult,
  DocumentParameterInput,
  FeatureAddResult,
  FeatureInputKind,
  FeatureInputRef,
  FeatureRecord,
  FeatureRecordInput,
  FeatureRecordUpdate,
  FeatureUpdateResult,
  DocumentOccurrence,
  DocumentOccurrenceInput,
  OccurrenceAddResult,
  OccurrenceBomFlag,
  OccurrencePlacement,
  OccurrenceSource,
  OCCURRENCE_BOM_FLAGS,
  OCCURRENCE_SOURCE_ID_MAX_LENGTH,
  SerializedBody,
  SerializedCadDocument,
  SerializedFeatureInputRef,
  SerializedFeatureRecord,
} from "./document";
export {
  addBody,
  updateBody,
  addDocumentCurve,
  addDocumentDatum,
  addDocumentSection,
  setDocumentSectionEnabled,
  DOCUMENT_SECTION_LIMIT,
  addDocumentParameter,
  addFeature,
  addOccurrence,
  updateOccurrence,
  removeOccurrence,
  getOccurrence,
  addDocumentConfiguration,
  removeDocumentConfiguration,
  updateDocumentConfiguration,
  addJoint,
  addMate,
  removeJoint,
  removeMate,
  createDocument,
  DOCUMENT_ERROR_CODES,
  FEATURE_INPUT_KINDS,
  getBody,
  getDocumentCurve,
  getDocumentDatum,
  getDocumentSection,
  getDocumentEntity,
  getDocumentSketch,
  addDocumentSketch,
  removeDocumentCurve,
  removeDocumentDatum,
  removeDocumentSketch,
  getDocumentReference,
  addDocumentReference,
  removeDocumentReference,
  getDocumentParameter,
  getFeature,
  parseCadDocument,
  parseFeatureInputRef,
  parseFeatureKind,
  removeBody,
  removeDocumentParameter,
  removeFeature,
  reorderFeature,
  serializeCadDocument,
  updateFeature,
} from "./document";
export type {
  DatumAxisEdge,
  DatumAxisFaceCylinder,
  DatumAxisTwoPoints,
  DatumCSysFrame,
  DatumError,
  DatumErrorCode,
  DatumKind,
  DatumPayload,
  DatumPlaneFaceOffset,
  DatumPlaneOriginFrame,
  DatumPlaneThreePoints,
  DatumPointPosition,
  DatumTopologyResolver,
  DatumVec3,
  ResolvedDatum,
  ResolvedDatumAxis,
  ResolvedDatumCSys,
  ResolvedDatumPlane,
  ResolvedDatumPoint,
} from "./datum";
export {
  DATUM_DIRECTION_EPSILON,
  DATUM_ERROR_CODES,
  DATUM_FORMAT_VERSION,
  DATUM_KINDS,
  datumAdd,
  datumCombine,
  datumCross,
  datumDot,
  datumLengthSquared,
  datumSubtract,
  isDatumKind,
  orthonormalDatumFrame,
  parseDatumPayload,
  resolveDatumPayload,
  serializeDatumPayload,
  unitDatumVec3,
} from "./datum";
export type {
  FeatureExecutionOutcome,
  FeatureExecutionRecord,
  FeatureExecutor,
  FeatureRegenerationState,
  FeatureRegenerationStatus,
  RegenerateInput,
  RegenerationError,
  RegenerationErrorCode,
  RegenerationResultMap,
  RegenerationRun,
  RegenerationStateMap,
  SerializedFeatureRegenerationStatus,
  SerializedRegenerationStateMap,
} from "./regeneration";
export {
  FEATURE_REGENERATION_STATES,
  initialRegenerationStates,
  isFeatureRegenerationState,
  markStale,
  parseRegenerationStates,
  REGENERATION_ERROR_CODES,
  regenerate,
  serializeRegenerationStates,
} from "./regeneration";
export type { ParseFailure, ParseResult } from "./result";
export { factorToCanonical } from "./units";
export { fail, ok } from "./result";
export {
  CAD_DOCUMENT_FORMAT_VERSION,
  CAD_NATIVE_FORMAT_VERSION,
  CAD_PROJECTION_FORMAT_VERSION,
} from "./version";
export type {
  KernelTessellationSource,
  ProjectionError,
  ProjectionErrorCode,
  RenderBounds,
  RenderCamera,
  RenderObject,
  RenderObjectId,
  RenderProjection,
  RenderVector3,
  SerializedRenderBounds,
  SerializedRenderCamera,
  SerializedRenderObject,
  SerializedRenderProjection,
} from "./projection";
export {
  boundsFromPositions,
  createRenderObjectId,
  createRenderProjection,
  bodyRendersInProjection,
  filterProjectionByBodyDisplay,
  parseRenderCamera,
  parseRenderObjectId,
  parseRenderProjection,
  withBodyAppearances,
  placementRenderObjectId,
  PROJECTION_ERROR_CODES,
  projectPlacedInstance,
  projectTessellation,
  RENDER_NORMAL_UNIT_TOLERANCE,
  RENDER_OBJECT_ID_PREFIX,
  renderObjectIdBodyId,
  serializeRenderProjection,
} from "./projection";
export type {
  CameraComparisonOptions,
  RenderObjectValidityOptions,
} from "./projection-assertions";
export {
  assertBoundsClose,
  assertCameraClose,
  assertIndicesEqual,
  assertPositionsClose,
  assertProjectionValid,
  assertRenderObjectValid,
  DEFAULT_PROJECTION_LINEAR_TOLERANCE_MM,
} from "./projection-assertions";
export type {
  EdgeSelectionReference,
  FaceSelectionReference,
  SelectionCategory,
  SelectionError,
  SelectionErrorCode,
  SelectionReference,
  SelectionState,
  SerializedSelectionReference,
  SerializedSelectionState,
  SolidSelectionReference,
  StableSelectionKind,
  StableSelectionReference,
  SyntheticSelectionKind,
  SyntheticSelectionReference,
  VertexSelectionReference,
} from "./selection";
export {
  beginRegeneration,
  clearSelection,
  createSelectionState,
  hoverSelection,
  isSyntheticSelectionReference,
  parseSelectionReference,
  parseSelectionState,
  pickSelection,
  SELECTION_CATEGORIES,
  SELECTION_ERROR_CODES,
  selectionReferenceBodyId,
  selectionReferenceKey,
  serializeSelectionReference,
  serializeSelectionState,
  STABLE_SELECTION_KINDS,
  SYNTHETIC_SELECTION_KINDS,
} from "./selection";
export type { SyntheticFace, SyntheticFaceGrouping } from "./synthetic-faces";
export {
  groupSyntheticFaces,
  syntheticFaceAnchor,
  syntheticFaceMeanNormal,
  syntheticFaceOfTriangle,
  SYNTHETIC_FACE_GROUPING_THRESHOLD_DEGREES,
} from "./synthetic-faces";
export type {
  MintReferenceOptions,
  PersistentEntityReference,
  ReferenceAnchor,
  ReferenceError,
  ReferenceErrorCode,
  ReferenceInvalidReason,
  ReferenceProvenance,
  ReferenceRepairRecord,
  ReferenceRepairStrategy,
  ReferenceValidity,
  ReferenceValidityRecord,
  ReferenceVector3,
  RepairReferenceOptions,
  ResolveReferenceOptions,
  SerializedReferenceAnchor,
  SerializedReferenceProvenance,
  SerializedReferenceRepairRecord,
  SerializedReferenceValidityRecord,
  SerializedTopologyEntityReference,
  SerializedTopologyGeometryDescriptor,
  SerializedTopologyIdentityPayload,
  TopologyEntityReference,
  TopologyEntitySnapshot,
  TopologyGeometryDescriptor,
  TopologyIdentityDatum,
  TopologyIdentityPayload,
  TopologyReferenceKind,
  TopologySnapshot,
  TopologyView,
  TransientSelectionReference,
} from "./persistent-reference";
export {
  applyReferenceValidity,
  disambiguateTopologyReference,
  isReferenceInvalidReason,
  isReferenceRepairStrategy,
  isReferenceValidity,
  mintTopologyReference,
  parseTopologyReference,
  provenanceIntact,
  REFERENCE_ERROR_CODES,
  REFERENCE_INVALID_REASONS,
  REFERENCE_MEASURE_RELATIVE_TOLERANCE,
  REFERENCE_POSITION_TOLERANCE_MM,
  REFERENCE_REPAIR_STRATEGIES,
  REFERENCE_VALIDITY_STATES,
  referenceProvenance,
  repairTopologyReference,
  resolveDocumentReference,
  resolveTopologyReference,
  serializeTopologyReference,
  TOPOLOGY_REFERENCE_KINDS,
  topologyGeometryMatches,
  topologyIdentityPayloadEqual,
  transientSelectionOf,
} from "./persistent-reference";
export type {
  ToolEventError,
  ToolEventErrorCode,
  ToolEventType,
  ToolInputEvent,
  ToolKeyboardEvent,
  ToolModifiers,
  ToolPick,
  ToolPointerEvent,
  ToolPointerEventType,
} from "./tool-events";
export {
  NO_TOOL_MODIFIERS,
  parseToolInputEvent,
  TOOL_EVENT_ERROR_CODES,
  TOOL_EVENT_TYPES,
  TOOL_POINTER_EVENT_TYPES,
  toolModifiers,
} from "./tool-events";
export type {
  ToolContext,
  ToolRuntime,
  ToolRuntimeOptions,
  ToolSelectionOperation,
} from "./tool-context";
export { createToolRuntime } from "./tool-context";
export type {
  CadTool,
  ToolCompletion,
  ToolCompletionDetail,
  ToolFailure,
  ToolFailureCode,
  ToolManager,
  ToolManagerOptions,
  ToolManagerPhase,
  ToolRegistryEntry,
  ToolStateBase,
  ToolTransition,
} from "./tool-manager";
export {
  createToolManager,
  registerTool,
  TOOL_FAILURE_CODES,
  TOOL_MANAGER_PHASES,
  toolFailure,
} from "./tool-manager";
export type { SelectToolState } from "./tool-select";
export { SELECT_TOOL_ID, selectTool } from "./tool-select";
export type { MeasureToolState } from "./tool-measure";
export { MEASURE_TOOL_ID, measureTool } from "./tool-measure";
export type { TranslateTarget, TranslateToolState } from "./tool-translate";
export {
  resolveTranslateTarget,
  TRANSLATE_FEATURE_KIND,
  TRANSLATE_TOOL_ID,
  translateTool,
} from "./tool-translate";
export type { RotateTarget, RotateToolState } from "./tool-rotate";
export {
  resolveRotateTarget,
  ROTATE_FEATURE_KIND,
  ROTATE_TOOL_ID,
  rotateTool,
} from "./tool-rotate";
export type {
  NativeFormatMigration,
  NativeMigrationError,
  NativeMigrationErrorCode,
} from "./native-migration";
export {
  migrateNativeCadDocument,
  NATIVE_FORMAT_MIGRATIONS,
  NATIVE_MIGRATION_ERROR_CODES,
  planNativeFormatMigrations,
  readNativeFormatVersion,
  runNativeFormatMigrations,
} from "./native-migration";
export type {
  NativeCadDocument,
  NativeCadDocumentParseError,
  NativeDocumentValidation,
  NativeFormatError,
  NativeFormatErrorCode,
  NativeFormatIssue,
  NativeFormatIssueCode,
  SerializedFeatureRollbackPoint,
  SerializedNativeCadDocument,
  SerializedNativeHistory,
} from "./native-format";
export {
  createNativeCadDocument,
  encodeNativeCadDocument,
  NATIVE_FORMAT_ERROR_CODES,
  NATIVE_FORMAT_ISSUE_CODES,
  parseNativeCadDocument,
  parseNativeCadDocumentFromBytes,
  parseNativeCadDocumentFromString,
  serializeNativeCadDocument,
  stringifyNativeCadDocument,
  validateNativeCadDocument,
} from "./native-format";
export {
  boundsExtents,
  formatBoundsExtents,
  selectedBoundsBody,
} from "./bounds";
export type { MassProperties, SectionFaceProperties } from "./mass-properties";
export {
  formatMassProperties,
  formatSectionCentroid,
  formatSurfaceArea,
  formatVolume,
  massPropertiesOf,
  sectionFacePropertiesOf,
} from "./mass-properties";
export type {
  DistanceError,
  DistanceErrorCode,
  MeasureEntity,
} from "./distance";
export {
  DISTANCE_ERROR_CODES,
  edgeEntity,
  formatMeasureDistance,
  measureDistance,
  measureEntityOfReference,
  measureEntityOfSnapshotEntity,
  measureSurfaceOfSyntheticFace,
  pointEntity,
  selectionDistance,
  surfaceEntity,
  vertexEntity,
} from "./distance";
export type {
  RadiusError,
  RadiusErrorCode,
  RadiusFitDetails,
  RadiusMeasure,
  RadiusPrecision,
} from "./radius";
export {
  fitCylindricalRadius,
  formatRadiusMeasure,
  RADIUS_ERROR_CODES,
  RADIUS_FIT_MAX_RESIDUAL_MM,
  selectionRadius,
  snapshotEntityRadius,
  storedRadius,
} from "./radius";
export type { PlacementRotation, PlacementTransform } from "./placement";
export {
  axisRotationTransform,
  composePlacementPath,
  composePlacementTransforms,
  IDENTITY_PLACEMENT_TRANSFORM,
  parsePlacementTransform,
  PLACEMENT_ORTHONORMAL_TOLERANCE,
  placementTransformBounds,
  placementTransformFromFrame,
  transformPlacementDirection,
  transformPlacementPoint,
} from "./placement";
export type {
  AssemblyDocumentRevision,
  AssemblyErrorCode,
  AssemblyError,
  AssemblyResolution,
  AssemblyResolverSeams,
  AssemblyStaleSource,
  AssemblyStaleness,
  PlacedBodyInstance,
} from "./assembly";
export {
  ASSEMBLY_ERROR_CODES,
  ASSEMBLY_INSTANCE_DEPTH_LIMIT,
  computeAssemblyStaleness,
  resolveAssemblyInstances,
  resolveOccurrencePlacement,
  resolveOccurrencePlacementFromFrames,
} from "./assembly";
export type {
  AssemblyExplodeError,
  AssemblyExplodeErrorCode,
  AssemblyExplodeInstance,
  AssemblyExplodeOffset,
  AssemblyExplodeState,
} from "./assembly-explode";
export {
  applyExplodeState,
  ASSEMBLY_EXPLODE_ERROR_CODES,
  ASSEMBLY_EXPLODE_PATH_DEPTH_LIMIT,
  parseExplodeState,
  radialExplodeOffsets,
  serializeExplodeState,
} from "./assembly-explode";
export type {
  AssemblyMotionError,
  AssemblyMotionErrorCode,
  AssemblyMotionJoint,
  AssemblyMotionJointKind,
  MotionClearanceSample,
  MotionProbeBounds,
} from "./assembly-motion";
export {
  applyMotionJoint,
  ASSEMBLY_MOTION_CAPABILITIES,
  ASSEMBLY_MOTION_ERROR_CODES,
  jointStationParameters,
  motionDragDecline,
  parseAssemblyMotionJoint,
  probeMotionClearance,
} from "./assembly-motion";
export type {
  AssemblyPatternError,
  AssemblyPatternErrorCode,
  PathOccurrencePatternInput,
} from "./assembly-pattern";
export {
  ASSEMBLY_PATTERN_CAPABILITIES,
  ASSEMBLY_PATTERN_ERROR_CODES,
  OCCURRENCE_PATTERN_INSTANCE_LIMIT,
  mirrorGeometryDecline,
  resolveCircularOccurrencePattern,
  resolveLinearOccurrencePattern,
  resolveMirroredOccurrencePlacement,
  resolvePathOccurrencePattern,
} from "./assembly-pattern";
export type {
  DrawingDocument,
  DrawingError,
  DrawingErrorCode,
  DrawingProjectionAngle,
  DrawingScale,
  DrawingSheet,
  DrawingSheetOrientation,
  DrawingSheetSize,
  DrawingView,
  DrawingViewGeometry,
  DrawingViewKind,
  ProjectedChain,
  SerializedDrawingDocument,
  SerializedDrawingScale,
  SerializedDrawingSheet,
  SerializedDrawingView,
  ViewBasis,
  ViewFrame,
} from "./drawing";
export {
  alignedViewPlacement,
  CAD_DRAWING_FORMAT_VERSION,
  DRAWING_ERROR_CODES,
  DRAWING_SCALES,
  DRAWING_SHEET_SIZES,
  DRAWING_SHEET_SIZE_NAMES,
  DRAWING_VIEW_EYE_DIRECTIONS,
  DRAWING_VIEW_KINDS,
  DRAWING_VIEW_UP_HINTS,
  parseDrawingDocument,
  roundTripDrawingDocument,
  scaleLength,
  serializeDrawingDocument,
  sheetDimensions,
  viewBasis,
  viewBasisForKind,
  viewFitsSheet,
  viewFrameFromGeometry,
} from "./drawing";
export type { OverlayMesh } from "./drawing-projection";
export {
  edgesOverlayProjection,
  edgesOverlayProjectionForKind,
  FEATURE_EDGE_DIHEDRAL_THRESHOLD_RAD,
} from "./drawing-projection";

export type {
  DrawingAnnotation,
  DrawingAnnotationId,
  DrawingAnnotationsErrorCode,
  DrawingAnnotationsParseError,
  DrawingDimension,
  DrawingDimensionId,
  DrawingDimensionOrigin,
  DrawingIdErrorCode,
  DrawingIdParseError,
  DrawingLinearOrientation,
  DrawingPoint,
  GdntCharacteristic,
  SerializedDrawingAnnotation,
  SerializedDrawingDimension,
  SerializedDrawingDimensionOrigin,
} from "./drawing-annotations";
export {
  DRAWING_ANNOTATIONS_ERROR_CODES,
  DRAWING_ID_ERROR_CODES,
  DRAWING_ID_PREFIXES,
  DRAWING_LINEAR_ORIENTATIONS,
  GDNT_CHARACTERISTICS,
  parseDrawingAnnotation,
  parseDrawingAnnotationId,
  parseDrawingDimension,
  parseDrawingDimensionId,
  serializeDrawingAnnotation,
  serializeDrawingDimension,
} from "./drawing-annotations";
export type {
  DrawingRevisionRow,
  DrawingSheetErrorCode,
  DrawingSheetParseError,
  DrawingSheetSetup,
  DrawingSheetTemplate,
  DrawingTitleBlock,
  SerializedDrawingSheetFurniture,
} from "./drawing-sheet";
export {
  DRAWING_SHEET_ERROR_CODES,
  DRAWING_SHEET_ORIENTATIONS,
  DRAWING_SHEET_SIZE_MM,
  DRAWING_SHEET_TEMPLATES,
  drawingSheetTemplateById,
  parseDrawingRevisionRow,
  parseDrawingSheetSetup,
  parseDrawingTitleBlock,
  serializeDrawingSheetFurniture,
  sheetDimensionsMm,
} from "./drawing-sheet";
export type {
  DrawingPictureGroup,
  DrawingPrimitive,
  DrawingSheetPicture,
} from "./drawing-presentation";
export {
  arrowHeadPolygonPoints,
  compareDrawingId,
  composeSheetPresentation,
  DRAWING_ARROW_LENGTH_MM,
  DRAWING_ARROW_WIDTH_MM,
  DRAWING_DIMENSION_OFFSET_MM,
  DRAWING_EXTENSION_GAP_MM,
  DRAWING_EXTENSION_OVERSHOOT_MM,
  DRAWING_FRAME_MARGIN_MM,
  DRAWING_REVISION_ROW_HEIGHT_MM,
  DRAWING_REVISION_TABLE_WIDTH_FRACTION,
  DRAWING_SMALL_TEXT_HEIGHT_MM,
  DRAWING_TEXT_HEIGHT_MM,
  DRAWING_TITLE_BLOCK_HEIGHT_MM,
  DRAWING_TITLE_BLOCK_WIDTH_FRACTION,
  formatDimensionValue,
  GDNT_SYMBOLS,
  holeCalloutText,
  presentDrawingAnnotation,
  presentDrawingDimension,
  presentSheetFurniture,
  sheetArcGeometry,
  type SheetArcGeometry,
  threadCalloutText,
  uprightTextTransform,
} from "./drawing-presentation";
export {
  drawingGroupMarkup,
  formatSvgNumber,
  serializeDrawingSheetSvg,
  serializeSheetPictureSvg,
} from "./drawing-svg";
export type { DrawingDimensionRecoveryOptions } from "./drawing-dimension-source";
export { recoverFeatureDimensions } from "./drawing-dimension-source";
export type {
  InterferenceCheckInput,
  InterferenceErrorCode,
  InterferenceError,
  InterferenceInstance,
  InterferencePair,
  InterferenceReport,
  InterferenceVolumeFn,
  SkippedInterferencePair,
} from "./assembly-interference";
export {
  checkAssemblyInterference,
  checkResolvedAssemblyInterference,
  INTERFERENCE_ERROR_CODES,
} from "./assembly-interference";
export type {
  AssemblyClearance,
  AssemblyClearanceError,
  AssemblyClearanceErrorCode,
  ClearanceCheckInput,
  ClearanceInstance,
  ClearanceMesh,
  ClearanceReport,
} from "./assembly-clearance";
export {
  ASSEMBLY_CLEARANCE_ERROR_CODES,
  checkAssemblyClearances,
  CLEARANCE_PRECISION,
} from "./assembly-clearance";
export type {
  InterferenceSnapshot,
  InterferenceSnapshotInput,
} from "./interference-report-export";
export {
  buildInterferenceSnapshot,
  formatSnapshotNumber,
  interferenceSnapshotDigest,
  INTERFERENCE_SNAPSHOT_KIND,
  INTERFERENCE_SNAPSHOT_VERSION,
  serializeInterferenceSnapshotHtml,
  serializeInterferenceSnapshotJson,
} from "./interference-report-export";
export type {
  DraftAnalysisError,
  DraftAnalysisErrorCode,
  DraftAnalysisInput,
  DraftAnalysisMesh,
  DraftAnalysisReport,
  DraftFace,
  DraftFaceClassification,
} from "./draft-analysis";
export {
  analyzeDraft,
  DRAFT_ANALYSIS_ERROR_CODES,
  DRAFT_BAND_COLORS,
  DRAFT_BAND_LIMIT_DEG,
} from "./draft-analysis";
export type {
  CurvatureComb,
  CurvatureCombInput,
  CurvatureCombSpike,
  CurvatureError,
  CurvatureErrorCode,
  PlanarPath,
  SurfaceCurvatureBand,
  SurfaceCurvatureBandCensus,
  SurfaceCurvatureBandsInput,
  SurfaceCurvatureBandsReport,
} from "./curvature";
export {
  CURVATURE_ERROR_CODES,
  sketchCurvatureComb,
  SURFACE_CURVATURE_BAND_COLORS,
  SURFACE_CURVATURE_BAND_LIMITS,
  surfaceCurvatureBands,
} from "./curvature";
export type {
  DocumentMassError,
  DocumentMassErrorCode,
  DocumentMassPropertiesInput,
  DocumentMassPropertiesReport,
  DocumentMaterialRecord,
  MassContribution,
  MaterialId,
} from "./document-mass";
export {
  documentMassProperties,
  DOCUMENT_MASS_ERROR_CODES,
  parseMaterialId,
} from "./document-mass";
export type {
  AssemblyMateError,
  AssemblyMateErrorCode,
  DocumentJoint,
  DocumentMate,
  JointFrame,
  JointKind,
  MateEndpoint,
  MateKind,
} from "./mates";
export {
  JOINT_KINDS,
  JOINT_REMAINING_DOF,
  jointMotionTransform,
  MATE_KINDS,
  MATE_VALUE_UNITS,
  normalizeJointAxis,
  parseAssemblyJoint,
  parseAssemblyMate,
} from "./mates";
export type {
  DocumentJointAddResult,
  DocumentJointInput,
  DocumentMateAddResult,
  DocumentMateInput,
} from "./document";
export type {
  AssemblySolveDiagnostic,
  AssemblySolveDiagnosticCode,
  AssemblySolveInput,
  AssemblySolveResult,
  AssemblySolveStatus,
  MateAnchor,
  MateAnchorTable,
} from "./mate-solver";
export {
  ASSEMBLY_SOLVE_DIAGNOSTIC_CODES,
  ASSEMBLY_SOLVE_STATUSES,
  jointDofSummary,
  MATE_DOF_RANK_TOLERANCE,
  MATE_MAX_ITERATIONS,
  MATE_RESIDUAL_TOLERANCE,
  referenceSolveCoincident,
  rotationVectorToMatrix,
  solveAssemblyMates,
} from "./mate-solver";
export type { OverlayClipPlane } from "./drawing-projection";
export type {
  CrossSectionLoop,
  SectionPlane,
  WorldChain,
} from "./drawing-section";
export {
  auxiliaryViewBasis,
  brokenOutOverlayProjection,
  DEFAULT_HATCH_ANGLE_RAD,
  DEFAULT_HATCH_SPACING_MM,
  detailCropGeometry,
  hatchLoops,
  meshPlaneCrossSection,
  polygonArea,
  projectedViewBasis,
  projectedViewBasisForKind,
  sectionOverlayProjection,
} from "./drawing-section";
export type {
  DrawingGeometryByView,
  PresentDrawingSheetOptions,
} from "./drawing-output";
export {
  BOM_COLUMN_WIDTHS,
  BOM_ROW_HEIGHT,
  DRAWING_PICTURE_STYLE,
  drawingSummary,
  presentDrawingDocument,
  presentDrawingSheet,
  serializeDrawingPdf,
  serializeDrawingSvg,
} from "./drawing-output";
export type {
  DrawingDxfDocument,
  DrawingDxfEntity,
  DrawingDxfError,
  DrawingDxfErrorCode,
  DrawingDxfLayer,
} from "./drawing-dxf";
export {
  buildDxfDocument,
  DRAWING_DXF_ERROR_CODES,
  DRAWING_DXF_LAYERS,
  parseDrawingDxf,
  serializeDrawingDxf,
  serializeParsedDrawingDxf,
} from "./drawing-dxf";
export type {
  DrawingBalloon,
  DrawingBomRow,
  DrawingBomTable,
  DrawingProjectedDirection,
  DrawingProjectionMethod,
  DrawingViewProjection,
  SerializedDrawingBalloon,
  SerializedDrawingBomRow,
  SerializedDrawingBomTable,
} from "./drawing";
export {
  DRAWING_PROJECTED_DIRECTIONS,
  DRAWING_PROJECTION_METHODS,
  numberBomItems,
} from "./drawing";
